name: "tests-nix-macos"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        platform:
          - macos-13
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v27
      with:
        install_url: "https://releases.nixos.org/nix/nix-2.17.1/install"
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v15
      with:
        name: timewave
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: "./run_tests.sh --no-cargo-build"
    - run: "nix --version"
    - run: "nix flake check"
    - run: "nix run . -- --help"
